title = "J Language Comment"
description = "C Jones' blog."
default_language = "en-US"
base_url = "https://www.calebjones.net"
compile_sass = true

# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true
highlight_theme = "solarized-light"

build_search_index = false
generate_rss = true

ignored_content = [".#*", "*.swp"]

[extra]
author = "C Jones"
